name = "Digest-xxHash"
badges = ["travis"]
module_maker="ModuleBuild"
license="bsd"
allow_pureperl=0
c_source=['src', 'ext/xxHash', 'ext/perl_math_int64']

[release]
pause_config = "C:/Strawberry/pause.upload"

[XSUtil]
needs_compiler_cpp=1
needs_compiler_c99=0
generate_ppport_h="ext/perl_math_int64/ppport.h"